name: CI

on:
  [ push, workflow_dispatch]
  # schedule:
  #   - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  deploy:
    timeout-minutes: 1
    needs: build
    concurrency: 
      cancel-in-progress: true
      group: deploy-group
    runs-on: ubuntu-latest
    steps:
    - name: deploy the code
      run: sleep 60