name: CI

on:
  [ push, workflow_dispatch]
  # schedule:
  #   - cron: "*/1 * * * *"

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world, alpine, python]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - os: ubuntu-20.04
            images: python12342
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: matrix values ${{ matrix.os }} & ${{ matrix.images}}
      run: |
        echo "print values of os ${{ matrix.os }}"
        echo "printing value of image ${{matrix.images}}"

  deploy:
    timeout-minutes: 1
    needs: build
    concurrency: 
      cancel-in-progress: true
      group: deploy-group
    runs-on: ubuntu-latest
    steps:
    - name: deploy the code
      run: sleep 30